---
title: "Firsts per State"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyverse)
library(lubridate)
library(cluster)

library(factoextra)

library(gridExtra)
library('ggplot2')
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages

library(ggthemes)
library(GGally)
library(dplyr)
library(readxl)
library(here)
library(skimr)
library(janitor)
library(broom)
library(tidyquant)
library(infer)
library(openintro)
library(kableExtra)
library(vroom)
library(leaflet)
library(moderndive)
library(car)
library(huxtable)
library(caret)
library(sf) # for geospatial visualisation
library(rsample)
library(extrafont)
library(vroom)
library(ggtext)
library(gapminder)
library(ggrepel)
library(patchwork)
library(gghighlight)
library(skimr)
library(ggplot2)
library(lubridate)
library(plotly)
```



load the data
```{r}
library(readr)
firsts<- read_csv("~/GitHub/am10.sg10/data/firsts_augmented.csv")
#glimpse(firsts)

firsts <- firsts %>% filter( country == "United States of America")

```


```{r}
label2 <- "New York State outnumbers \n the other states"
my_colours <- c("grey80", "dodgerblue1") #setting colors

states <- firsts %>% 
  filter(!is.na(state)) %>% #removing NAs from the data
  count(state) %>% 
  mutate(tot  = sum(n), pct = n/sum(n)*100,
         NY = ifelse(`state` == "New York", TRUE, FALSE)) %>%
  filter(pct > 2) %>% 
  arrange(desc(n))

states$pct <- paste(round(states$pct), "%", sep="") 
  
states <- states[-c(28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43),]

ggplot(states, aes(x =  n, 
                   #order by counts and fill new york
                     y = reorder(state, n), fill = NY)) +  
  geom_col() + 
  scale_fill_manual(values = my_colours) + 
   #adding the percentages on the columns
  geom_text(
    aes(label = pct),
    colour = "green4",
    size = 6,
    nudge_x = 1,
    nudge_y = 0,
    hjust = 0.5,
    family="Lato")+
  #adding the comment on new york 
  geom_text(
    data = data.frame(x = 25, y = 9.5, label = label2),
    aes(x = x, y = y, label = label2),
    colour="dodgerblue1",
    family="Lato",
    size = 4,
    hjust = 0.5,
    lineheight = .6,
    inherit.aes = FALSE)+
  #adding the arrow pointing on the New York Column
  geom_curve(
    data = data.frame(x = 25, y = 10, xend = 30, yend = 19.2),
    mapping = aes(x = x, y = y, xend = xend, yend = yend),
    colour = "grey15",
    size = 0.5,
    curvature = 0.25,
    arrow = arrow(length = unit(2, "mm"), type = "closed"),
    inherit.aes = FALSE) +
  #adding titles and subtitles
  labs(colour = "stoppage",
       title = "The most liberal state takes the highest number of firsts",
       subtitle = "Over time, East Coast states have gathered more firsts",
       caption = "",
       x = "Percentage African American Firsts in the USA",
       y = "") +
  
  theme_classic()+ #theme
  theme(legend.position = "none",#removing the legend
        plot.title = element_text(size = 23, face = "bold", colour = "dodgerblue1"), #adding attributes for the title
        plot.subtitle = element_text(size = 15),#subtitle size
        axis.title = element_text(size = 12), #Axis title size
        axis.text.x = element_blank(), #axis text attributes
        axis.text.y = element_text(angle = 0, hjust = 1, size = 12), #axis text attributes
        axis.ticks = element_blank(),
        axis.line  = element_blank())#remove the tick marks
        
#Due to the growth in population in America being focused on the East Coast until around the 1920s, much earlier than parts for central and western America, it can be seen from the bar chart above that the number of firsts have been significantly higher. This could be due to the migration of communities over time. 

#The data collected starts from 1800, during which the percentage of "free" blacks was not uniform, the northern eastern region had a much higher percentage of free blacks throughout the 1800s which may have also contributed to the stark difference between the west and east during that time. The ablution of slavery in the 1860s additionally saw a huge impact in the growth of the firsts in African American communities. 

#New York had the highest count in firsts. New York State was one of the pioneer states to abolish slavery in 1827( It was officially abolished in 1863 in the US), and New York City had one of the largest concentration of free African Americans, with many institutions being established to support the community. 


```

