---
title: "Marco"
author: "Marco Laube"
date: "25/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}

library(tidyverse)
library(vroom)
library(janitor)
library(sf)
library(here)
library(extrafont)
library(ggtext)
library(lubridate)
library(urbnmapr)
library(readxl)
library(stringr)

loadfonts(device="win")

```

# TO DOS:

- agree on story line
- agree on style and colors

# The Data

We analyze **African-American Firsts**, celebrating their achievements breaking the colour barrier across a wide range of topics.  
The data was scraped from [Wikipedia](https://en.wikipedia.org/wiki/List_of_African-American_firsts) (see `scraping_data.R`).

# Load the data

```{r}

firsts <- read_csv(here("../data/firsts_augmented.csv"), 
                   col_types = cols(year = col_integer(), 
                                    id_num = col_integer())) %>% 
  clean_names()

glimpse(firsts)

```

# Visualise a Map

```{r}

# get / convert shapefiles

states_sf <- get_urbn_map("states", sf = TRUE)
states_sf$geometry

# transfrom geometry to 4326, or pairs of latitude/longitude numbers
states_sf <-  states_sf %>% 
  st_transform(4326) # transfrom to WGS84, latitude/longitude
states_sf$geometry

# convert firsts to an sf object
firsts_sf <- firsts %>% 
  drop_na(lng, lat, gender) %>% 
  filter(country == "United States of America") %>% 
  # filter irrelevant lng/lat
  filter(lng > -140) %>% 
  st_as_sf(coords = c('lng', 'lat'), 
           crs = st_crs(states_sf))
firsts_sf$geometry

# count how many achievers were born in each state
states_sf <- states_sf %>%
  mutate(count = lengths(
    st_contains(states_sf, 
                firsts_sf))) 

```


```{r}

# Visualise where Achievers where born in the US
ggplot() +
    # draw polygons from states shapefile
    geom_sf(data = states_sf, fill = "grey99", color = "black")+
    # add points from firsts shapefile
    geom_sf(
      data = firsts_sf, aes(fill = gender), size = 2, shape = 21,
      show.legend = TRUE
    ) + 
    scale_fill_manual(values = c("#000461", "#AD8C00")) +
    theme_minimal()+
    coord_sf(datum = NA) + #remove coordinates
    labs(title = "Most achievers were born in the East!") +
    # hrbrthemes::theme_ft_rc(grid="", strip_text_face = "bold") +
    theme(axis.text = element_blank()) +
    # theme(strip.text = element_text(color = "white"))+
    NULL

```

```{r}

# Visualise how many achievers were born in each state

ggplot(data = states_sf, aes(fill = count)) +
  geom_sf(color = "#04314D") +
  scale_fill_gradient(low = "#ffffff", high = "#04314D", name = NULL) +
  theme_minimal()+
  coord_sf(datum = NA) + #remove coordinates
  labs(title = "Most achievers were born in the East!") +
  # hrbrthemes::theme_ft_rc(grid="", strip_text_face = "bold") +
  theme(axis.text = element_blank()) +
  NULL

```

```{r}

# Timeline combined with a lesson in History
# Inspiration:
# https://www.history.com/topics/black-history/black-history-milestones

firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1) +
  geom_vline(xintercept = 1901, # Washington, Carver & Du Bois + NAACP + UNIA + Harlem Renaissance
             color = "#AD8C00", size=1) +
  geom_vline(xintercept = 1941, # WWII begining and aftermath
             color = "#AD8C00", size=1) +
  geom_vline(xintercept = 1963, # i have a dream / civil rights movement +  Civil Rights Act of 1964 + Fair Housing Act, .....
             color = "#AD8C00", size=1) +
  geom_vline(xintercept = 1986, # Oprah Winfrey start + Los Angeles Riots + Million Man March
             color = "#AD8C00", size=1) +
  geom_vline(xintercept = 2008, # President Barack Obama
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL

# first plot
firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL
  
firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1901, # Washington, Carver & Du Bois + NAACP + UNIA + Harlem Renaissance
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL


firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1901, # Washington, Carver & Du Bois + NAACP + UNIA + Harlem Renaissance
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1941, # WWII begining and aftermath
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL

firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1901, # Washington, Carver & Du Bois + NAACP + UNIA + Harlem Renaissance
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1941, # WWII begining and aftermath
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1963, # i have a dream / civil rights movement +  Civil Rights Act of 1964 + Fair Housing Act, .....
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL

firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1901, # Washington, Carver & Du Bois + NAACP + UNIA + Harlem Renaissance
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1941, # WWII begining and aftermath
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1963, # i have a dream / civil rights movement +  Civil Rights Act of 1964 + Fair Housing Act, .....
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1986, # Oprah Winfrey start + Los Angeles Riots + Million Man March
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL

firsts %>% 
  ggplot(aes(x = year)) +
  geom_histogram(boundary = 1861, binwidth = 5, color = "white", fill = "#000461") +
  geom_vline(xintercept = 1861, # civil war
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1901, # Washington, Carver & Du Bois + NAACP + UNIA + Harlem Renaissance
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1941, # WWII begining and aftermath
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1963, # i have a dream / civil rights movement +  Civil Rights Act of 1964 + Fair Housing Act, .....
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 1986, # Oprah Winfrey start + Los Angeles Riots + Million Man March
             color = "#AD8C00", size=1, alpha = 0.2) +
  geom_vline(xintercept = 2008, # President Barack Obama
             color = "#AD8C00", size=1) +
  theme_minimal() + 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  NULL

```

