---
title: "Test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(vroom)
library(extrafont)
library(ggtext)
library(lubridate)
```

## Graph 1 

```{r graph_1}

year_int <- firsts_augmented %>% 
  mutate(ints = cut(year ,breaks = 28)) %>%
  group_by(ints) %>%
  count() %>%
  mutate(
    civil = ifelse(ints == "(1942,1952]", TRUE, FALSE)
  )

my_colours <- c("grey80", "#4292c6")

year_int %>%
  ggplot(aes(x = ints, y = n, fill = civil)) +
  geom_col() +
  scale_fill_manual(values = my_colours) +
  scale_x_discrete(breaks = c("(1746,1756]", "(1756,1766]", "(1766,1775]", "(1775,1785]","(1785,1795]", "(1795,1805]","(1814,1824]", "(1824,1834]", "(1834,1844]", "(1844,1854]","(1854,1863]", "(1863,1873]","(1873,1883]", "(1883,1893]", "(1893,1903]", "(1903,1912]","(1912,1922]", "(1922,1932]","(1932,1942]", "(1942,1952]", "(1952,1961]", "(1961,1971]","	(1971,1981]", "(1981,1991]","(1991,2000]","(2000,2010]","(2010,2020]"), labels = c("1751", "1761","1771","1780","1790","1880","1819","1829","1839","1849","1859","1868","1878","1888","1898","1908","1917","1927","1937","1947","1957","1966","1976","1986","1996","2005","2015")) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90)) +
  labs(title="Spike in number of firsts after the civil rights movement!",
       x="years",
       y="count of firsts")
  
```

## Graph 2

```{r graph_2}

gender_split <- firsts_augmented %>%
  select(year,gender) %>%
  group_by(year,gender) %>%
  count() %>%
  arrange(year) 

#create pyramid histogram
gender_split %>%
  ggplot(aes(x = year,
           y = ifelse(gender == "female", 
                      n, -n),
           fill = gender)) +
  geom_col(width = 1, color = "white") +
  #scale_x_discrete(breaks = c("2018-01", "2018-07", "2019-01", "2019-07","2020-01", "2020-07"), labels = c("Jan 2018", "July 2018","Jan 2019","July 2019","Jan 2020","July 2020")) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none"
  ) +
  theme(text=element_text(size=12, family="Times New Roman"))+
  theme(plot.title.position = "plot") +
  scale_fill_manual(values = c("#fa9fb5","#9ecae1")) +
  
  # change font colour 
  labs(title = "<b> Although racial equality has improved over the years, gender inequality still persists over the years</b><br>
       <span style = 'font-size:12pt'> More males than females throughout the years/ alternative: large spike in female first after black women's movement in 1960 </span>",
       x= "",
       y = "",
       fill="Gender")+
  
  theme(
    plot.title.position = "plot",
    plot.title = element_textbox_simple(size=16),
    axis.title.y = element_text(size=14),
    axis.text = element_text(size=10),
    legend.position = "right") +
  NULL
```

## Graph 3

```{r graph_3}

first_age <- firsts_augmented %>%
  select(year,bday) %>%
  drop_na(bday) %>%
  mutate(bday_year=year(bday),
         age_first=year-bday_year) %>%
  select(age_first) %>%
  mutate(ints = cut(age_first ,breaks = c(1,10,20,30,40,50,60,70,80,90,100,110))) %>%
  group_by(ints) %>%
  count() %>%
  mutate(
    leader = ifelse(ints == "(20,30]", TRUE, FALSE)
  )
  
my_colours <- c("grey80", "#e34a33")

first_age %>%
  ggplot(aes(x = ints, y = n, fill = leader)) +
  geom_col() +
  scale_fill_manual(values = my_colours) +
  # scale_x_discrete(breaks = c("(1746,1756]", "(1756,1766]", "(1766,1775]", "(1775,1785]","(1785,1795]", "(1795,1805]","(1814,1824]", "(1824,1834]", "(1834,1844]", "(1844,1854]","(1854,1863]", "(1863,1873]","(1873,1883]", "(1883,1893]", "(1893,1903]", "(1903,1912]","(1912,1922]", "(1922,1932]","(1932,1942]", "(1942,1952]", "(1952,1961]", "(1961,1971]","	(1971,1981]", "(1981,1991]","(1991,2000]","(2000,2010]","(2010,2020]"), labels = c("1751", "1761","1771","1780","1790","1880","1819","1829","1839","1849","1859","1868","1878","1888","1898","1908","1917","1927","1937","1947","1957","1966","1976","1986","1996","2005","2015")) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90)) +
  labs(title="Young people are the ones who break the status quo!",
       x="age",
       y="count of firsts")

```

## Graph 4

```{r graph_4}

category_state <- firsts_augmented %>%
  select(state,category) %>%
  drop_na(state) %>%
  group_by(state, category) %>%
  count() %>%
  filter(state== "Vermont" | state== "Texas")


category_state %>%
  ggplot(aes(x = category, y = n)) +
  facet_wrap(~state) +
  geom_col() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90)) +
  labs(title="Texas, the state with the highest population of Black people has alot \n more firsts than Vermont, the state dominated with White people",
       x="age",
       y="count of firsts")

```